Repository openfun/marion, pull requests merged in 2021-03, with the labels that each got.

#11 👷(circleci) package howard module
  .circleci/config.yml
  src/howard/setup.cfg
  src/marion/setup.cfg
Labels: FUN, improvement

#14 🚸(project) add issue and pull request templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Support_question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: improvement, needs review

#17 ♻️(project) move marion from a Django project to an app
  .circleci/config.yml
  Dockerfile
  Makefile
  bin/pylint
  bin/pytest
  docker-compose.yml
  env.d/development/common
  sandbox/__init__.py
  sandbox/asgi.py
  sandbox/manage.py
  sandbox/settings.py
  sandbox/urls/__init__.py
  sandbox/urls/debug.py
  sandbox/wsgi.py
  src/howard/howard/issuers/realisation.py
  src/howard/howard/templates/marion/realisation.css
  src/howard/howard/templates/marion/realisation.html
  src/marion/marion/admin.py
  src/marion/marion/apps.py
  src/marion/marion/defaults.py
  src/marion/marion/documents/issuers/__init__.py
  src/marion/marion/documents/migrations/0002_auto_20200910_1453.py
  src/marion/marion/documents/urls/__init__.py
  src/marion/marion/documents/urls/debug.py
  src/marion/marion/exceptions.py
  src/marion/marion/factories.py
  src/marion/marion/issuers/__init__.py
  src/marion/marion/issuers/base.py
  src/marion/marion/issuers/dummy.py
  src/marion/marion/migrations/0001_initial.py
  src/marion/marion/migrations/__init__.py
  src/marion/marion/models.py
  src/marion/marion/serializers.py
  src/marion/marion/static/marion/noun_Check_3612574.svg
  src/marion/marion/templates/marion/dummy.css
  src/marion/marion/templates/marion/dummy.html
  src/marion/marion/tests/__init__.py
  src/marion/marion/tests/issuers/__init__.py
  src/marion/marion/tests/issuers/test_base.py
  src/marion/marion/tests/test_defaults.py
  src/marion/marion/tests/test_models.py
  src/marion/marion/tests/test_serializers.py
  src/marion/marion/tests/test_utils.py
  src/marion/marion/tests/test_views.py
  src/marion/marion/urls/__init__.py
  src/marion/marion/urls/debug.py
  src/marion/marion/utils.py
  src/marion/marion/views.py
  src/marion/setup.cfg
Labels: improvement

#21 🔧(packages) improve dependencies management
  src/marion/setup.cfg
Labels: improvement, needs review

#23 📦(project) update python package names
  src/howard/setup.cfg
  src/marion/setup.cfg
Labels: FUN, needs review
