Repository openfun/marion, pull requests merged in 2021-06, with the labels that each got.

#43 ♻️ (howard) rename and resize invoice fun logo
  src/howard/CHANGELOG.md
  src/howard/howard/static/howard/logo-fun.png
  src/howard/howard/static/howard/logo-invoice.png
  src/howard/howard/templates/howard/invoice.html
Labels: improvement, needs review

#42 ✨(howard) add certificate issuer
  src/howard/CHANGELOG.md
  src/howard/howard/defaults.py
  src/howard/howard/issuers/__init__.py
  src/howard/howard/issuers/certificate.py
  src/howard/howard/templates/howard/certificate.css
  src/howard/howard/templates/howard/certificate.html
  src/howard/howard/tests/issuers/test_certificate.py
  src/howard/locale/fr_FR/LC_MESSAGES/django.mo
  src/howard/locale/fr_FR/LC_MESSAGES/django.po
  src/marion/marion/models.py
Labels: feature, needs review

#46 🐛(howard) fix sentence translation failure
  src/howard/CHANGELOG.md
  src/howard/howard/locale/fr_FR/LC_MESSAGES/django.po
  src/howard/howard/templates/howard/certificate.html
Labels: bug

#47 Release Howard 0.2.2
  src/howard/CHANGELOG.md
  src/howard/setup.cfg
Labels: FUN, needs review, release

#48 🐛(howard) fix path to compile translations
  Makefile
  src/howard/CHANGELOG.md
  src/howard/howard/locale/fr_FR/LC_MESSAGES/django.mo
  src/howard/howard/locale/fr_FR/LC_MESSAGES/django.po
Labels: bug

#49 Release Howard 0.2.3
  src/howard/CHANGELOG.md
  src/howard/setup.cfg
Labels: FUN, needs review, release

#52 🔖(patch) bump howard release to 0.2.4
  src/howard/CHANGELOG.md
  src/howard/setup.cfg
Labels: FUN, needs review, release
